# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - '386'
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
  # hooks:
  #   post: git diff

archive:
  # replacements:
  #   darwin: Darwin
  #   linux: Linux
  #   windows: Windows
  #   386: i386
  #   amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  github:
    owner: goldeneggg
    name: homebrew-tap
  commit_author:
    name: Fuminori Sakamoto
    email: jpshadowapps@gmail.com
  folder: Formula
  homepage: 'https://github.com/goldeneggg/gat'
  description: 'Utility tool of concatnating and printing file to various services'
  test: |
    system '#{bin}/gat -v'

# TODO: support for execution on Mac
# nfpm:
#   license: MIT
#   maintainer: Fuminori Sakamoto
#   homepage: https://github.com/goldeneggg/gat
#   formats:
#     - deb
#     - rpm
