language: go

go:
  - 1.11.x

sudo: false

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
