language: go

go:
  - 1.3
  - 1.4
  - 1.4.1
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - 1.7.1

before_install:
  - go get github.com/tools/godep
  - godep get

script:
- godep go test -race -v ./...

sudo: false
