language: go

go:
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master

# addons:
#   apt:
#     packages:
#     # require for nfpm task of goreleaser
#     - rpm

sudo: false

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/golang/lint/golint
  # these are require for goreleaser's CI as follows
  # - curl -sL -o goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/v0.101.0/goreleaser_Linux_x86_64.tar.gz
  # - tar -zxf goreleaser.tar.gz

install:
  - go mod download

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

# FIXME: this is not work. See: https://travis-ci.org/goldeneggg/gat/jobs/495808850#L890
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
