language: go

go:
  - 1.3
  - tip

before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/tools/godep
  - godep get

script:
- godep go vet -n ./...
- godep go test -race ./...
